---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# test-release-process
name: '📄 Generate Pull Request'
description: 'Generates a pull request'

inputs:
  token:
    description: 'Github token with the required permissions'
    type: 'string'
    required: true

runs:
  using: "composite"
  steps:
    # yamllint disable-line rule:line-length
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: 'Write the date to a file'
      shell: bash
      run: |
        # Write the date to a file
        date=$(date)
        echo "date=$date" >> $GITHUB_ENV
        echo "$date" > date.txt
        message=$(echo $date | awk '{print $1" "$2" "$3" "$4}')
        echo "message=$message" >> $GITHUB_ENV
        echo '# Generating Pull Request' >> "$GITHUB_STEP_SUMMARY"
        echo 'Generating Pull Request'
        echo "Writing date to file: $date > date.txt" >> "$GITHUB_STEP_SUMMARY"
        echo "Writing date to file: $date > date.txt"

    - name: 'Detect change'
      id: detect
      shell: bash
      run: |
        # Detect repository changes
        if [[ `git status --porcelain` ]]; then
          echo 'Changes made to repository ✅'
        else
          echo 'No changes made to repository 💬'
        fi

    - name: 'Raise Pull Request'
      if: steps.detect.outputs.changed == 'true'
      id: raise-change
      # yamllint disable rule:line-length
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ env.message }}
        signoff: 'true'
        sign-commits: 'true'
        branch: auto-pr
        delete-branch: true
        title: ${{ env.message }}
        body: |
          Updated repository.

          ## Update summary

          echo ${{ env.date }} > date.txt"

          *Auto-generated by [lfreleng-actions/test-release-process/action.yaml][1]*

          [1]: https://github.com/lfreleng-actions/test-release-process/blob/main/action.yaml
        labels: |
          automated pr
        draft: false
