# SPDX-FileCopyrightText: 2025 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = "date.txt"
precedence = "closest"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
SPDX-License-Identifier = "Apache-2.0"
