---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on a tag push event
name: "Test Release Process"

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      # Triggered only by semantic tags push
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  promote-release:
    name: 'Promote Draft Release'
    # yamllint disable-line rule:line-length
    if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[release]')
    runs-on: "ubuntu-24.04"
    permissions:
      contents: write
      # id-token: write
    steps:
      - name: "Promote draft release"
        # yamllint disable-line rule:line-length
        uses: modeseven-lfreleng-actions/draft-release-promote-action@initial-update # ToDo: Testing
