---
# SPDX-FileCopyrightText: 2025 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

name: 'Release Drafter'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  # pull_request is required for autolabeler
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  # pull_request_target is required for autolabeler on PRs from forks
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  update-release:
    name: 'Update Draft Release'
    permissions:
      # write permission is required to create releases
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5
    steps:
      - name: 'Harden runner 🔒'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: 'Update Draft Release'
        # yamllint disable-line rule:line-length
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
